config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/bertranddelouis/SlipNearResults:
      branch: main
      repo: https://github.com/bertranddelouis/SlipNearResults
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/bertranddelouis/SlipNearResults git:
        commands:
        - /usr/bin/env sh .sqa/script.woozy-ecru-guppy.sh
        container: qc.acc_slimy-purple-schnauzer
  QC.Doc:
    repos:
      github.com/bertranddelouis/SlipNearResults find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-dandelion-millipede.sh
        container: qc.doc_sleazy-alizarin-tapir
      github.com/bertranddelouis/SlipNearResults git:
        commands:
        - /usr/bin/env sh .sqa/script.lanky-aqua-audemer.sh
        container: qc.doc_hazy-cobalt-hedgehog
      github.com/bertranddelouis/SlipNearResults markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.snippy-sangria-shrimp.sh
        container: qc.doc_clammy-wisteria-dachshund
  QC.Lic:
    repos:
      github.com/bertranddelouis/SlipNearResults licensee:
        commands:
        - /usr/bin/env sh .sqa/script.skanky-seashell-crab.sh
        container: qc.lic_surly-chocolate-bulldog
  QC.Ver:
    repos:
      github.com/bertranddelouis/SlipNearResults get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.messy-brass-lobster.sh
        container: qc.ver_pasty-seashell-burmese
timeout: 5400
